//! Ollama-compatible HTTP route handlers.

use crate::api::types::*;
use crate::dashboard::log_store::LogStore;
use crate::middleware::logging::next_request_id;
use crate::proxy::{stream, BackendRunner};
use crate::usage::{QuotaExceeded, TokenUsageTracker};
use axum::{
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Response},
    Json,
};
use std::sync::Arc;
use std::time::Instant;
use tokio::sync::{mpsc, Mutex};
use tracing::{debug, error, info, warn};

/// Shared application state passed to handlers.
#[derive(Clone)]
pub struct AppState {
    pub runner: Arc<Mutex<BackendRunner>>,
    pub model_name: String,
    pub log_store: LogStore,
    pub token_usage_tracker: Option<Arc<TokenUsageTracker>>,
}

// ---------------------------------------------------------------------------
// Health / metadata
// ---------------------------------------------------------------------------

pub async fn health() -> &'static str {
    debug!("GET / health check");
    "Ollama is running"
}

pub async fn health_head() -> StatusCode {
    debug!("HEAD / health check");
    StatusCode::OK
}

pub async fn version() -> Json<VersionResponse> {
    info!("GET /api/version");
    Json(VersionResponse {
        version: "0.1.0-ttyproxy".into(),
    })
}

pub async fn list_tags(State(state): State<AppState>) -> Json<TagsResponse> {
    let resp = TagsResponse {
        models: vec![ModelInfo {
            name: state.model_name.clone(),
            model: state.model_name.clone(),
            modified_at: now_iso(),
            size: 0,
            digest: model_digest(),
            details: ModelDetails::default_claude(),
        }],
    };
    info!(model_count = resp.models.len(), "GET /api/tags");
    debug!(response = %serde_json::to_string_pretty(&resp).unwrap_or_default(), "tags response");
    Json(resp)
}

pub async fn show_model(
    State(state): State<AppState>,
    Json(body): Json<ShowRequest>,
) -> Json<ShowResponse> {
    let model = body.model.as_deref().unwrap_or(&state.model_name);
    info!(model = %model, "POST /api/show");
    let resp = ShowResponse {
        modelfile: format!(
            "# Modelfile generated by ttyproxy\nFROM {}",
            state.model_name
        ),
        parameters: "claude-code CLI proxy".into(),
        template: "{{ .Prompt }}".into(),
        details: ModelDetails::default_claude(),
    };
    debug!(response = %serde_json::to_string_pretty(&resp).unwrap_or_default(), "show response");
    Json(resp)
}

// ---------------------------------------------------------------------------
// Chat
// ---------------------------------------------------------------------------

pub async fn chat(State(state): State<AppState>, Json(req): Json<ChatRequest>) -> Response {
    let request_id = next_request_id();
    let start = Instant::now();
    let prompt = messages_to_prompt(&req.messages);
    let is_stream = req.stream.unwrap_or(true);
    let model = req
        .model
        .as_deref()
        .unwrap_or(&state.model_name)
        .to_string();
    let message_count = req.messages.len();

    info!(
        request_id = %request_id,
        model = %model,
        stream = is_stream,
        message_count = message_count,
        prompt_bytes = prompt.len(),
        options = ?req.options,
        "POST /api/chat"
    );
    for (i, msg) in req.messages.iter().enumerate() {
        debug!(
            request_id = %request_id,
            msg_index = i,
            role = %msg.role,
            content_bytes = msg.content.len(),
            content = %msg.content,
            "chat message"
        );
    }
    debug!(request_id = %request_id, assembled_prompt = %prompt, "prompt for claude");

    eprintln!("\n--- [ttyproxy] /api/chat [{request_id}] ---");
    eprintln!("  model={model}  stream={is_stream}  messages={message_count}");

    let user_preview = req
        .messages
        .iter()
        .rev()
        .find(|m| m.role == "user")
        .map(|m| m.content.chars().take(200).collect::<String>())
        .unwrap_or_default();

    if !user_preview.is_empty() {
        eprintln!("  user: {user_preview}");
    }

    // Log to dashboard
    state.log_store.log_incoming_request(
        &request_id,
        "/api/chat",
        &model,
        &format!(
            "{} messages, stream={}, prompt={}B",
            message_count,
            is_stream,
            prompt.len()
        ),
        &prompt,
    );

    if let Some(response) =
        quota_preflight_chat_response(&state, &request_id, &model, is_stream, start)
    {
        return response;
    }

    let runner = state.runner.lock().await;

    if is_stream {
        match runner.run_streaming_chat(&req.messages, &request_id).await {
            Ok(rx) => {
                info!(request_id = %request_id, "streaming started");
                let body = stream::chat_stream_body(
                    model.clone(),
                    rx,
                    request_id.clone(),
                    state.log_store.clone(),
                );
                Response::builder()
                    .header("Content-Type", "application/x-ndjson")
                    .header("Transfer-Encoding", "chunked")
                    .body(body)
                    .unwrap()
            }
            Err(e) => {
                error!(request_id = %request_id, error = %e, "backend error (stream)");
                state
                    .log_store
                    .log_error(&request_id, "/api/chat", &e.to_string());
                (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response()
            }
        }
    } else {
        match runner.run_blocking_chat(&req.messages, &request_id).await {
            Ok(text) => {
                let elapsed = start.elapsed();
                info!(
                    request_id = %request_id,
                    response_bytes = text.len(),
                    elapsed_ms = elapsed.as_millis() as u64,
                    "chat response ready"
                );
                debug!(request_id = %request_id, response = %text, "response content");

                eprintln!("  response ({} bytes)", text.len());
                eprintln!(
                    "--- [ttyproxy] done [{request_id}] ({:.1}s) ---",
                    elapsed.as_secs_f64()
                );

                state.log_store.log_outgoing_response(
                    &request_id,
                    "/api/chat",
                    &model,
                    &format!("{}B in {:.1}s", text.len(), elapsed.as_secs_f64()),
                    &text,
                    elapsed.as_millis() as u64,
                    text.len() as u64,
                    None,
                );

                Json(ChatResponse {
                    model,
                    created_at: now_iso(),
                    message: ChatMessage::assistant(text),
                    done: true,
                    done_reason: Some("stop".into()),
                    total_duration: Some(elapsed.as_nanos() as u64),
                    load_duration: Some(0),
                    prompt_eval_count: Some(0),
                    prompt_eval_duration: Some(0),
                    eval_count: Some(0),
                    eval_duration: Some(elapsed.as_nanos() as u64),
                })
                .into_response()
            }
            Err(e) => {
                error!(request_id = %request_id, error = %e, "backend error (blocking)");
                state
                    .log_store
                    .log_error(&request_id, "/api/chat", &e.to_string());
                (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

pub async fn generate(State(state): State<AppState>, Json(req): Json<GenerateRequest>) -> Response {
    let request_id = next_request_id();
    let start = Instant::now();

    let mut prompt = req.prompt.clone();
    if let Some(sys) = &req.system {
        prompt = format!("[System]\n{sys}\n\n{prompt}");
    }
    let is_stream = req.stream.unwrap_or(true);
    let model = req
        .model
        .as_deref()
        .unwrap_or(&state.model_name)
        .to_string();

    info!(
        request_id = %request_id,
        model = %model,
        stream = is_stream,
        prompt_bytes = prompt.len(),
        has_system = req.system.is_some(),
        options = ?req.options,
        "POST /api/generate"
    );
    debug!(
        request_id = %request_id,
        prompt = %req.prompt,
        system = ?req.system,
        assembled_prompt = %prompt,
        "generate details"
    );

    eprintln!("\n--- [ttyproxy] /api/generate [{request_id}] ---");
    eprintln!("  model={model}  stream={is_stream}");
    eprintln!(
        "  prompt: {}...",
        prompt.chars().take(200).collect::<String>()
    );

    state.log_store.log_incoming_request(
        &request_id,
        "/api/generate",
        &model,
        &format!("stream={}, prompt={}B", is_stream, prompt.len()),
        &prompt,
    );

    if let Some(response) =
        quota_preflight_generate_response(&state, &request_id, &model, is_stream, start)
    {
        return response;
    }

    let runner = state.runner.lock().await;

    if is_stream {
        match runner.run_streaming(&prompt, &request_id).await {
            Ok(rx) => {
                info!(request_id = %request_id, "streaming started");
                let body = stream::generate_stream_body(
                    model.clone(),
                    rx,
                    request_id.clone(),
                    state.log_store.clone(),
                );
                Response::builder()
                    .header("Content-Type", "application/x-ndjson")
                    .header("Transfer-Encoding", "chunked")
                    .body(body)
                    .unwrap()
            }
            Err(e) => {
                error!(request_id = %request_id, error = %e, "backend error (stream)");
                state
                    .log_store
                    .log_error(&request_id, "/api/generate", &e.to_string());
                (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response()
            }
        }
    } else {
        match runner.run_blocking(&prompt, &request_id).await {
            Ok(text) => {
                let elapsed = start.elapsed();
                info!(
                    request_id = %request_id,
                    response_bytes = text.len(),
                    elapsed_ms = elapsed.as_millis() as u64,
                    "generate response ready"
                );
                debug!(request_id = %request_id, response = %text, "response content");

                eprintln!("  response ({} bytes)", text.len());
                eprintln!(
                    "--- [ttyproxy] done [{request_id}] ({:.1}s) ---",
                    elapsed.as_secs_f64()
                );

                state.log_store.log_outgoing_response(
                    &request_id,
                    "/api/generate",
                    &model,
                    &format!("{}B in {:.1}s", text.len(), elapsed.as_secs_f64()),
                    &text,
                    elapsed.as_millis() as u64,
                    text.len() as u64,
                    None,
                );

                Json(GenerateResponse {
                    model,
                    created_at: now_iso(),
                    response: text,
                    done: true,
                    done_reason: Some("stop".into()),
                    context: Some(vec![]),
                    total_duration: Some(elapsed.as_nanos() as u64),
                    load_duration: Some(0),
                    prompt_eval_count: Some(0),
                    prompt_eval_duration: Some(0),
                    eval_count: Some(0),
                    eval_duration: Some(elapsed.as_nanos() as u64),
                })
                .into_response()
            }
            Err(e) => {
                error!(request_id = %request_id, error = %e, "backend error (blocking)");
                state
                    .log_store
                    .log_error(&request_id, "/api/generate", &e.to_string());
                (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Stubs
// ---------------------------------------------------------------------------

pub async fn embeddings(Json(req): Json<EmbeddingsRequest>) -> Json<EmbeddingsResponse> {
    warn!(
        model = ?req.model,
        has_prompt = req.prompt.is_some(),
        has_input = req.input.is_some(),
        "POST /api/embeddings - stub"
    );
    Json(EmbeddingsResponse {
        model: req.model.unwrap_or_else(|| "claude-code:latest".into()),
        embeddings: vec![vec![0.0; 384]],
        total_duration: 0,
        load_duration: 0,
        prompt_eval_count: 0,
    })
}

pub async fn pull_model() -> Json<serde_json::Value> {
    info!("POST /api/pull - stub");
    Json(serde_json::json!({ "status": "success" }))
}

pub async fn delete_model() -> StatusCode {
    info!("DELETE /api/delete - stub");
    StatusCode::OK
}

pub async fn copy_model() -> StatusCode {
    info!("POST /api/copy - stub");
    StatusCode::OK
}

fn quota_preflight_chat_response(
    state: &AppState,
    request_id: &str,
    model: &str,
    is_stream: bool,
    start: Instant,
) -> Option<Response> {
    let exceeded = quota_exceeded(state, request_id, "/api/chat")?;
    let message = quota_exceeded_message(&exceeded);

    if is_stream {
        let (tx, rx) = mpsc::channel(1);
        let _ = tx.try_send(message);
        drop(tx);
        let body = stream::chat_stream_body(
            model.to_string(),
            rx,
            request_id.to_string(),
            state.log_store.clone(),
        );
        return Some(
            Response::builder()
                .header("Content-Type", "application/x-ndjson")
                .header("Transfer-Encoding", "chunked")
                .body(body)
                .unwrap(),
        );
    }

    let elapsed = start.elapsed();
    state.log_store.log_outgoing_response(
        request_id,
        "/api/chat",
        model,
        &format!("quota exhausted in {:.1}s", elapsed.as_secs_f64()),
        &message,
        elapsed.as_millis() as u64,
        message.len() as u64,
        None,
    );

    Some(
        Json(ChatResponse {
            model: model.to_string(),
            created_at: now_iso(),
            message: ChatMessage::assistant(message),
            done: true,
            done_reason: Some("stop".into()),
            total_duration: Some(elapsed.as_nanos() as u64),
            load_duration: Some(0),
            prompt_eval_count: Some(0),
            prompt_eval_duration: Some(0),
            eval_count: Some(0),
            eval_duration: Some(elapsed.as_nanos() as u64),
        })
        .into_response(),
    )
}

fn quota_preflight_generate_response(
    state: &AppState,
    request_id: &str,
    model: &str,
    is_stream: bool,
    start: Instant,
) -> Option<Response> {
    let exceeded = quota_exceeded(state, request_id, "/api/generate")?;
    let message = quota_exceeded_message(&exceeded);

    if is_stream {
        let (tx, rx) = mpsc::channel(1);
        let _ = tx.try_send(message);
        drop(tx);
        let body = stream::generate_stream_body(
            model.to_string(),
            rx,
            request_id.to_string(),
            state.log_store.clone(),
        );
        return Some(
            Response::builder()
                .header("Content-Type", "application/x-ndjson")
                .header("Transfer-Encoding", "chunked")
                .body(body)
                .unwrap(),
        );
    }

    let elapsed = start.elapsed();
    state.log_store.log_outgoing_response(
        request_id,
        "/api/generate",
        model,
        &format!("quota exhausted in {:.1}s", elapsed.as_secs_f64()),
        &message,
        elapsed.as_millis() as u64,
        message.len() as u64,
        None,
    );

    Some(
        Json(GenerateResponse {
            model: model.to_string(),
            created_at: now_iso(),
            response: message,
            done: true,
            done_reason: Some("stop".into()),
            context: Some(vec![]),
            total_duration: Some(elapsed.as_nanos() as u64),
            load_duration: Some(0),
            prompt_eval_count: Some(0),
            prompt_eval_duration: Some(0),
            eval_count: Some(0),
            eval_duration: Some(elapsed.as_nanos() as u64),
        })
        .into_response(),
    )
}

fn quota_exceeded(state: &AppState, request_id: &str, endpoint: &str) -> Option<QuotaExceeded> {
    let tracker = state.token_usage_tracker.as_ref()?;
    if !tracker.enforces_quota() {
        return None;
    }

    match tracker.quota_exceeded() {
        Ok(Some(exceeded)) => {
            warn!(
                request_id = %request_id,
                endpoint = %endpoint,
                openclaw_instance = %exceeded.snapshot.openclaw_instance,
                llm_token_quota = ?exceeded.snapshot.llm_token_quota,
                llm_token_used = exceeded.snapshot.llm_token_used,
                remaining_tokens = ?exceeded.snapshot.remaining_tokens,
                "returning quota exhausted assistant response"
            );
            Some(exceeded)
        }
        Ok(None) => None,
        Err(error) => {
            warn!(
                request_id = %request_id,
                endpoint = %endpoint,
                error = %error,
                "token quota preflight failed; allowing request"
            );
            None
        }
    }
}

fn quota_exceeded_message(exceeded: &QuotaExceeded) -> String {
    let snapshot = &exceeded.snapshot;
    match snapshot.llm_token_quota {
        Some(quota) => format!(
            "This OpenClaw instance has used all assigned AI credits ({} of {} tokens used). Please top up AI credits in 2ndBrain before sending more requests.",
            snapshot.llm_token_used, quota
        ),
        None => "This OpenClaw instance has used all assigned AI credits. Please top up AI credits in 2ndBrain before sending more requests.".into(),
    }
}
